name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore SteamQueryNet
    - name: Build
      run: dotnet build --no-restore SteamQueryNet
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName!~SteamQueryNet.Tests.IntegrationTests SteamQueryNet
